version: "3.9"

services:
  astrocorner-db:
    container_name: astrocorner-db
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=astrocorner
    ports:
      - target: 3306
        published: 3307