spring:
  datasource:
    url: jdbc:mysql://localhost:3306/astrocorner
    username: # environment variable
    password: # environment variable
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  security:
    jwt:
      access:
        secret: SECRET_KEY_FOR_ACCESS_TOKEN
        expiration-ms: 900000 # 15 min
      refresh:
        secret: SECRET_KEY_FOR_REFRESH_TOKEN
        expiration-ms: 1296000000 # 15 days