spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/astrocorner  # provided by docker container
    username: root                                # provided by docker container
    password: root                                # provided by docker container
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    username: uhello
    password: phello
    port: 4025

app:
  security:
    jwt:
      access:
        secret: SECRET_KEY_FOR_ACCESS_TOKEN
        expiration-ms: 15000 # 900000 # 15 min
      refresh:
        secret: SECRET_KEY_FOR_REFRESH_TOKEN
        expiration-ms: 30000 # 1296000000 # 15 days